=== ValentinDORMANN/ul-glo4002-a16-equipe-m2001/flycheckin/reservation/src/ressources/DATA/DTD/BookingList.dtd
<!ELEMENT bookingList (booking*)>
<!ELEMENT booking (bookingDate+, bookingConfirm+, paymentLocation+, flightDate+, flightNumber+, companyName?)>
<!ATTLIST booking number CDATA #REQUIRED>
<!ELEMENT bookingDate (#PCDATA)>
<!ELEMENT bookingConfirm (#PCDATA)>
<!ELEMENT paymentLocation (#PCDATA)>
<!ELEMENT flightDate (#PCDATA)>
<!ELEMENT flightNumber (#PCDATA)>
<!ELEMENT companyName (#PCDATA)>

=== ValentinDORMANN/ul-glo4002-a16-equipe-m2001/flycheckin/reservation/src/ressources/DATA/BookingList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE passengers SYSTEM "DTD/BookingList.dtd">
<bookingList>
  <booking number="33782">
    <bookingDate>2016-09-25</bookingDate>
    <bookingConfirm>A44919</bookingConfirm>
    <paymentLocation>/payments/da39a3aa5e6b4b0d3255chag21118210afd80709</paymentLocation>
    <flightDate>2016-10-25</flightDate>
    <flightNumber>AF-315</flightNumber>
    <companyName>Air France</companyName>
  </booking>
</bookingList>
