=== ValentinDORMANN/ul-glo4002-a16-equipe-m2001/flycheckin/reservation/src/ressources/DATA/DTD/Passengers.dtd
<!ELEMENT passengers (passenger*)>
<!ELEMENT passenger (name+, firstname+, age+, passportNumber+)>
<!ATTLIST passenger hashCode CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT passportNumber (#PCDATA)>

=== ValentinDORMANN/ul-glo4002-a16-equipe-m2001/flycheckin/reservation/src/ressources/DATA/Passengers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE passengers SYSTEM "DTD/Passengers.dtd" >
<passengers>
  <passenger hashCode="John/DOE/B0074994">
    <name>DOE</name>
    <firstname>John</firstname>
    <age>48</age>
    <passportNumber>B0074994</passportNumber>
  </passenger>
  <passenger hashCode="">
    <name>MAHUGNON</name>
    <firstname>Taylor</firstname>
    <age>12</age>
    <passportNumber>B0074584</passportNumber>
  </passenger>
  <passenger hashCode="">
    <name>DORMANN</name>
    <firstname>Valentin</firstname>
    <age>22</age>
    <passportNumber>F0015994</passportNumber>
  </passenger>
  <passenger hashCode="">
    <name>VOILLOT</name>
    <firstname>Virgil</firstname>
    <age>23</age>
    <passportNumber>F0079634</passportNumber>
  </passenger>
  <passenger hashCode="">
    <name>KHALOUD</name>
    <firstname>Siham</firstname>
    <age>25</age>
    <passportNumber>M4124994</passportNumber>
  </passenger>
  <passenger hashCode="">
    <name>TCHOUTOUO</name>
    <firstname>Hypo</firstname>
    <age>42</age>
    <passportNumber>C1256994</passportNumber>
  </passenger>
</passengers>
